security:
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api-doc:
            pattern: ^/api/doc(.json)?$
            security: false
        auth: 
            pattern: ^/api/(login|refresh|register)$
            security: false
        api:
            anonymous: true
            stateless: true
            pattern: ^/api
            guard:
                authenticators:
                    - App\Security\JWTAuthenticator
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

#TODO: ROLE UŻYTKOWNIKÓW